use std::{ops::Add, str::FromStr};

use actix_web::{HttpResponse, Responder, post, web};
use chrono::{Duration, Utc};
use maud::html;
use serde::Deserialize;
use sqlx::Connection;
use uuid::Uuid;
use validator::Validate;

use crate::{
    config::AppData,
    database::repository,
    email::{
        EmailAddress,
        blocklist::ApprovedEmailAddress,
        mailer::{EmailBody, OutgoingEmail},
        partials,
    },
    endpoints::ApiError,
    extractors::auth::Auth,
    types::api::ApiResponse,
};

#[derive(Deserialize, Validate)]
struct StartEmailChangePayload {
    #[validate(email, length(max = 512))]
    email: String,
    force: Option<bool>,
}

#[post("v1/me/email/change")]
pub async fn start_email_change(
    auth: Auth,
    json: web::Json<StartEmailChangePayload>,
    data: web::Data<AppData>,
) -> Result<impl Responder, ApiError> {
    let mailer = data.mailer().ok_or(ApiError::NotImplemented)?;
    let front_url = data.front_url();

    if front_url.is_empty() {
        return Err(ApiError::NotImplemented);
    }

    let developer = auth.developer()?;
    let now = Utc::now();

    {
        let mut conn = data.db().acquire().await?;

        let existing_email_login =
            repository::developers::find_login_data_for_developer(developer.id, &mut conn)
                .await?
                .ok_or_else(|| {
                    ApiError::Conflict(
                        "You don't have your email address setup. Use /v1/me/email/setup".into(),
                    )
                })?;

        let exists = repository::email_change_requests::get_one(developer.id, &mut conn).await?;

        let force = json.force.unwrap_or(false);
        let exists_and_is_valid = exists
            .as_ref()
            .is_some_and(|exists| exists.expires_at.gt(&now));

        if !force && exists_and_is_valid {
            return Err(ApiError::Conflict(
            "You already have a pending email change request. Please confirm you want to invalidate it.".into(),
        ));
        }

        if exists.is_some() {
            repository::email_change_requests::delete(developer.id, &mut conn).await?;
        }

        if existing_email_login.email.to_lowercase() == json.email.to_lowercase() {
            return Err(ApiError::BadRequest(
                "Your new email cannot be the same as your current email".into(),
            ));
        }
    }

    let email = ApprovedEmailAddress::parse(
        EmailAddress::from_str(&json.email).expect("email validated by json struct"),
        data.email_blocklist(),
    )?;

    let expiry_date = now.add(Duration::minutes(30));

    let uuid = Uuid::new_v4();

    let endpoint = format!("{}/email/change/verify?token={}", data.front_url(), uuid);

    // TODO: maybe make a good looking email template sometime in the future
    let html = html! {
        (partials::salute(&developer.display_name))
        p {
            "Someone (hopefully you) requested to change the email address for your Geode SDK developer account to this one."
        }
        p {
            "If you didn't request this, you can safely ignore this email."
        }
        p {
            "Visit"
            a href=(endpoint) { (endpoint) }
            "to confirm this email address."
        }
        p {
            "This link expires in 30 minutes."
        }
        (partials::footer())
    }
    .into_string();

    let outgoing = OutgoingEmail {
        to: email.clone(),
        subject: "Email change request | Geode SDK".into(),
        body: EmailBody::html_with_autogenerated_text(html)?,
    };

    mailer
        .send(&outgoing)
        .await
        .inspect_err(|e| tracing::error!("{:?}", e))?;

    let mut conn = data.db().acquire().await?;
    let mut tx = conn.begin().await?;
    repository::email_change_requests::delete(developer.id, &mut tx).await?;
    repository::email_change_requests::create(developer.id, &uuid, &email, &expiry_date, &mut tx)
        .await?;
    tx.commit().await?;

    Ok(HttpResponse::Created().json(ApiResponse {
        payload: "".to_string(),
        error: "".into(),
    }))
}
