use std::{ops::Add, str::FromStr};

use actix_web::{HttpResponse, Responder, post, web};
use chrono::{Duration, Utc};
use maud::html;
use serde::Deserialize;
use sqlx::Connection;
use utoipa::ToSchema;
use uuid::Uuid;
use validator::Validate;

use crate::{
    auth, config::AppData, database::repository, email::{
        EmailAddress,
        blocklist::ApprovedEmailAddress,
        mailer::{EmailBody, OutgoingEmail},
        partials,
    }, endpoints::ApiError, extractors::auth::Auth, types::api::ApiResponse,
};

#[derive(Deserialize, Validate, ToSchema)]
struct StartEmailChangePayload {
    #[validate(email, length(max = 512))]
    email: String,
    password: String,
    force: Option<bool>,
}

/// Finalize email configuration
#[utoipa::path(
    request_body = StartEmailChangePayload,
    tag = "developers",
    responses(
        (status = 201, description = "Request created", body = inline(ApiResponse<String>)),
        (status = 400, description = "New email is same as old email / Invalid password provided"),
        (status = 401, description = "Unauthorized"),
        (status = 404, description = "Setup request not found"),
        (status = 409, description = "You already have a pending request, retry with \"force\" in JSON to confirm / Email address is not setup")
    ),
    security(
        ("bearer_token" = [])
    )
)]
#[tracing::instrument(skip_all)]
#[post("v1/me/email/change")]
pub async fn start_email_change(
    auth: Auth,
    json: web::Json<StartEmailChangePayload>,
    data: web::Data<AppData>,
) -> Result<impl Responder, ApiError> {
    json.validate()?;

    let mailer = data.mailer().ok_or(ApiError::NotImplemented)?;
    let front_url = data.front_url();

    if front_url.is_empty() {
        return Err(ApiError::NotImplemented);
    }

    let developer = auth.developer()?;
    let now = Utc::now();

    let email = ApprovedEmailAddress::parse(
        EmailAddress::from_str(&json.email.to_lowercase())
            .map_err(|_| ApiError::BadRequest("invalid email address".into()))?,
        data.email_blocklist(),
    )?;

    let existing_email_login = {
        let mut conn = data.db().acquire().await?;

        let existing_email_login =
            repository::developers::find_login_data_for_developer(developer.id, &mut conn)
                .await?
                .ok_or_else(|| {
                    ApiError::Conflict(
                        "You don't have your email address setup. Use /v1/me/email/setup".into(),
                    )
                })?;

        let exists = repository::email_change_requests::find_one(developer.id, &mut conn).await?;

        let force = json.force.unwrap_or(false);
        let exists_and_is_valid = exists
            .as_ref()
            .is_some_and(|exists| exists.expires_at.gt(&now));

        if !force && exists_and_is_valid {
            return Err(ApiError::Conflict(
                "You already have a pending email change request. Please confirm you want to invalidate it.".into(),
            ));
        }

        if existing_email_login.email.to_lowercase() == email.email().to_string().to_lowercase() {
            return Err(ApiError::BadRequest(
                "Your new email cannot be the same as your current email".into(),
            ));
        }

        existing_email_login
    };

    let password_hash = existing_email_login.password_hash.clone();
    let pepper = data.password_hash_pepper().cloned();

    if !auth::password::verify(password_hash, json.password.clone(), pepper).await? {
        return Err(ApiError::BadRequest("Invalid password".into()));
    }

    let expiry_date = now.add(Duration::minutes(30));
    let uuid = Uuid::new_v4();
    let endpoint = format!("{}/email/change/verify?token={}", data.front_url(), uuid);

    // TODO: maybe make a good looking email template sometime in the future
    let html = html! {
        (partials::salute())
        p {
            "Someone (hopefully you) requested to change the email address for the Geode SDK developer account " (&developer.username) " to this one."
        }
        p {
            "If you didn't request this, you can safely ignore this email."
        }
        p {
            "Visit"
            a href=(endpoint) { (endpoint) }
            "to confirm this email address."
        }
        p {
            "This link expires in 30 minutes."
        }
        (partials::footer())
    }
    .into_string();

    let outgoing = OutgoingEmail {
        to: email.clone(),
        subject: "Email change request | Geode SDK".into(),
        body: EmailBody::html_with_autogenerated_text(html)?,
    };

    mailer
        .send(&outgoing)
        .await
        .inspect_err(|e| tracing::error!("{:?}", e))?;

    let mut conn = data.db().acquire().await?;
    let mut tx = conn.begin().await?;
    repository::email_change_requests::delete(developer.id, &mut tx).await?;
    repository::email_change_requests::create(developer.id, &uuid, &email, &expiry_date, &mut tx)
        .await?;
    tx.commit().await?;

    Ok(HttpResponse::Created().json(ApiResponse {
        payload: "".to_string(),
        error: "".into(),
    }))
}

#[derive(Deserialize, ToSchema)]
struct FinalizeEmailChange {
    request_id: String,
}

/// Finalize email change
#[utoipa::path(
    request_body = FinalizeEmailChange,
    tag = "developers",
    responses(
        (status = 204, description = "Email changed"),
        (status = 401, description = "Unauthorized"),
        (status = 404, description = "Change request not found"),
        (status = 409, description = "You don't actually an email setup or you already have the requested address (should never happen)")
    ),
    security(
        ("bearer_token" = [])
    )
)]
#[tracing::instrument(skip_all)]
#[post("v1/me/email/change/verify")]
pub async fn finalize_email_change(
    data: web::Data<AppData>,
    json: web::Json<FinalizeEmailChange>,
    auth: Auth,
) -> Result<impl Responder, ApiError> {
    let mailer = data.mailer().ok_or(ApiError::NotImplemented)?;
    let developer = auth.developer()?;

    let request_id = Uuid::try_parse(&json.request_id).map_err(|_| {
        ApiError::NotFound(
            "The request associated with this ID either does not exist or has expired".into(),
        )
    })?;

    let now = Utc::now();

    let mut conn = data.db().acquire().await?;
    let mut tx = conn.begin().await?;

    let not_found_msg = "The request associated with this ID either does not exist or has expired";

    let request = repository::email_change_requests::find_one_by_token(&request_id, &mut tx)
        .await?
        .ok_or(ApiError::NotFound(not_found_msg.into()))?;

    if request.developer_id != developer.id {
        return Err(ApiError::NotFound(not_found_msg.into()));
    }

    if request.expires_at.lt(&now) {
        return Err(ApiError::NotFound(not_found_msg.into()));
    }

    let existing = repository::developers::find_by_email(&request.new_email, &mut tx).await?;

    if existing.is_some_and(|e| e.id != developer.id) {
        return Err(ApiError::Conflict(
            "Someone else already has this email address".into(),
        ));
    }

    let current_email = repository::developers::get_email(developer.id, &mut tx).await?
        .ok_or(ApiError::Conflict("Somehow, you don't have an email address, but manged to get this far. Congratulations! You broke the index!".into()))?;

    // Who knows, maybe the blocklist gets updated while the request is running
    let email = ApprovedEmailAddress::parse(
        EmailAddress::from_str(&request.new_email.to_lowercase())
            .inspect_err(|e| tracing::error!("failed to parse email from EmailChangeRequest: {e}"))
            .map_err(|e| {
                ApiError::InternalError(format!("Failed to read email from request: {e}"))
            })?,
        data.email_blocklist(),
    )?;

    repository::developers::change_email(developer.id, &current_email, &email, &mut tx).await?;

    tx.commit().await?;

    let masked_email = email.email().to_masked_string();

    let confirmation_email = html!(
        (partials::salute())
        p {
            "You have changed your email for your Geode SDK developer account " (&developer.username) " to " (&masked_email) "."
        }
        p {
            "If you didn't request this, please contact an index admin immediately."
        }
        (partials::footer())
    ).into_string();

    match EmailAddress::from_str(&current_email) {
        Ok(old) => {
            let outgoing = OutgoingEmail {
                // No need for a blocklist, this is an already approved email, also doesn't return Err
                // without a blacklist
                to: ApprovedEmailAddress::parse(old, None).unwrap(),
                subject: "Email change successful | Geode SDK".into(),
                body: EmailBody::html_with_autogenerated_text(&confirmation_email)
                    .inspect_err(|e| tracing::error!("Failed to autogenerate text from html: {e}"))
                    .unwrap_or(EmailBody::Html(confirmation_email))
            };

            let _ = mailer
                .send(&outgoing)
                .await
                .inspect_err(|e| tracing::error!("{:?}", e));
        },
        Err(e) => tracing::error!("stored email failed to parse, skipping change notification: {e}")
    };

    Ok(HttpResponse::NoContent())
}
