name: Setup rust
description: Installs rust for cross-compilation on ARM

runs:
  using: "composite"
  steps:
    - name: Install ARM cross-compilation tools
      shell: bash
      run: sudo apt-get update && sudo apt-get install --assume-yes --no-install-recommends g++-aarch64-linux-gnu

    - name: Install rust
      shell: bash
      run: |
        rustup toolchain install stable --profile minimal
        rustup target add aarch64-unknown-linux-gnu
