name: Setup rust
description: Installs rust for cross-compilation on ARM and x86_64

inputs:
  install-arm:
    description: 'Whether to install ARM cross-compilation tools'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install rust
      shell: bash
      run: |
        rustup toolchain install stable --profile minimal
        if [ "${{ inputs.install-arm }}" == "true" ]; then
          rustup target add aarch64-unknown-linux-gnu
        fi
