name: "geode-index"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: geode-index
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    networks:
      - dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./:/app
  postgres:
    container_name: geode-postgres
    image: postgres:14-alpine3.20
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=geode
      - POSTGRES_USER=geode
      - POSTGRES_DB=geode
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev
volumes:
  postgres-db:
networks:
  dev:
    driver: bridge