use std::{pin::Pin, sync::Arc};

use crate::email::blocklist::ApprovedEmailAddress;

pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

#[derive(Clone, Debug, thiserror::Error)]
pub enum MailerError {
    #[error("invalid message: {0}")]
    InvalidMessage(String),
    #[error("failed to send: {0}")]
    SendError(String),
}

pub type MailerResult<T> = Result<T, MailerError>;

#[derive(Debug)]
pub enum EmailBody {
    Plaintext(String),
    Html(String),
    Multipart { text: String, html: String },
}

impl EmailBody {
    pub fn html_with_autogenerated_text(html: impl Into<String>) -> MailerResult<Self> {
        let html = html.into();
        let text = html2text::from_read(html.as_bytes(), 80)
            .inspect_err(|e| tracing::error!("{:?}", e))
            .map_err(|e| MailerError::InvalidMessage(e.to_string()))?;

        Ok(EmailBody::Multipart { text, html })
    }
}

#[derive(Debug)]
pub struct OutgoingEmail {
    pub to: ApprovedEmailAddress,
    pub subject: String,
    pub body: EmailBody,
}

pub trait MailerBackend: Send + Sync {
    fn send<'a>(&'a self, email: &'a OutgoingEmail) -> BoxFuture<'a, MailerResult<()>>;
}

#[derive(Clone)]
pub struct Mailer {
    backend: Arc<dyn MailerBackend>,
}

impl Mailer {
    pub fn new(backend: Arc<dyn MailerBackend>) -> Self {
        Mailer { backend }
    }

    pub async fn send(&self, email: &OutgoingEmail) -> MailerResult<()> {
        self.backend.send(email).await?;
        Ok(())
    }
}
