-- Add up migration script here

-- dependencies
ALTER TABLE dependencies
ADD COLUMN windows BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE dependencies
ADD COLUMN mac_arm BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE dependencies
ADD COLUMN mac_intel BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE dependencies
ADD COLUMN android32 BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE dependencies
ADD COLUMN android64 BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE dependencies
ADD COLUMN ios BOOLEAN NOT NULL DEFAULT TRUE;

-- incompatibilities
ALTER TABLE incompatibilities
ADD COLUMN windows BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE incompatibilities
ADD COLUMN mac_arm BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE incompatibilities
ADD COLUMN mac_intel BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE incompatibilities
ADD COLUMN android32 BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE incompatibilities
ADD COLUMN android64 BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE incompatibilities
ADD COLUMN ios BOOLEAN NOT NULL DEFAULT TRUE;

