name: Deploy Index

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Create ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.INDEX_SSH_PORT }} -H ${{ secrets.INDEX_SERVER }} > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -p ${{ secrets.INDEX_SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }} \
            "cd ${{ secrets.INDEX_DIR }} && docker compose pull && docker compose up -d --wait"
